# Generated by Django 4.1.7 on 2023-10-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='nullable',
            field=models.TextField(default='text', verbose_name='Текст'),
            preserve_default=False,
        ),
    ]
