# Generated by Django 4.1.7 on 2023-10-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_testmodel_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='nullable',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
